name: auther
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.7+3

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  otp: ^3.1.2
  crypto: ^3.0.3
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.2

  mobile_scanner: ^5.2.1
  qr_flutter: ^4.1.0

  shared_preferences: ^2.3.2
  local_auth: ^2.3.0
  path_provider: ^2.1.4
  file_picker: ^8.1.3
  flutter_launcher_icons: ^0.13.1

  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.6.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto-Serif
      fonts:
        - asset: fonts/Roboto-Serif.ttf

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icon_bg.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon_fg.png" # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/icon.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#000000"